development:
  secret_key_base: 9dbe0ae589eb763a4d08e0ee407f77854dffeaf18cbbfe31b2d982168a6b679d6200ac034deca732b3099ba00171bff591f44ca3970d26cf91ce1ddff2467dba
  stripe_publishable_key: pk_test_iPpIFeArU9hDl6LGJdgBaTSN
  stripe_secret_key: sk_test_409TtTJwdU9q1bddDBsvAy3v
  stripe_client_id: ca_8aIwOrJ8fIEn2m9zfbPKK7wVTYIukqRA
  fee_percentage: 0.1

test:
  secret_key_base: 9dbe0ae589eb763a4d08e0ee407f77854dffeaf18cbbfe31b2d982168a6b679d6200ac034deca732b3099ba00171bff591f44ca3970d26cf91ce1ddff2467dba

production:
  stripe_publishable_key: pk_test_iPpIFeArU9hDl6LGJdgBaTSN
  stripe_secret_key: sk_test_409TtTJwdU9q1bddDBsvAy3v
  stripe_client_id: ca_8aIwOrJ8fIEn2m9zfbPKK7wVTYIukqRA
  fee_percentage: 0.1